name: Setup SDK
runs:
  using: "composite"
  steps:
    - name: Set up Sonar tools
      uses: ./.github/workflows/actions/sonar-tools
    - name: Sonar Scan Begin # Sonar Begin
      shell: pwsh
      run: |
        ./.sonar/scanner/dotnet-sonarscanner begin /k:"$env:SONAR_PROJECT_KEY" /o:"$env:SONAR_ORGANIZATION" /d:sonar.token="$env:SONAR_TOKEN" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.host.url="$env:SONAR_HOST_URL"