version: '3'

name: drn-app
services:
  sample:
    container_name: drn-sample
    image: ${DOCKER_REGISTRY-}sample:0.0.1
    build:
      context: .
      dockerfile: Sample.Hosted/Dockerfile
    ports:
      - 81:8080