version: '3'

name: drn-app
services:
  sample:
    container_name: drn-sample
    image: ${DOCKER_REGISTRY-}sample:0.0.1
    build:
      context: .
      dockerfile: Sample.Hosted/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5999
    ports:
      - "5999:5999/udp"
      - "5999:5999/tcp"
    volumes:
      - ~/.aspnet/https:/https #map certificates
      #- %USERPROFILE%\.aspnet\https:/https  #map certificates for windows
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets #map secrets for linux & macos
      #- %APPDATA%\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets  #map secrets for windows
