name: Docker Publish All
inputs:
  username:
    required: true
  password:
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Publish Nexus
      uses: ./.github/workflows/actions/docker-publish
      with:
        project-name: DRN.Nexus.Hosted
        image-repository-name: drn-project-nexus
    - name: Publish Sample
      uses: ./.github/workflows/actions/docker-publish
      with:
        project-name: Sample.Hosted
        image-repository-name: drn-project-sample