name: drn-graylog
services:
  # https://graylog.org/post/announcing-graylog-6-3-1
  # https://hub.docker.com/_/mongo/
  # Source codes under this folder is obtained/derived from https://github.com/Graylog2/docker-compose/blob/main/open-core/docker-compose.yml 
  # and have same license restrictions with original source codes. 
  mongodb:
    image: "mongo:6.0.25"
    restart: "on-failure"
    container_name: drn-graylog-mongo
    networks:
      - graylog
    volumes:
      - graylog-mongodb_data:/data/db
      - graylog-mongodb_config:/data/configdb 
    deploy:
      resources:
        limits:
          memory: 1g
          
  # For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
  # Please take a look at the README at the top of this repo or the regular docs for more info.
  # Graylog Data Node: https://hub.docker.com/r/graylog/graylog-datanode
  datanode:
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:6.3.2}"
    container_name: drn-graylog-datanode
    hostname: "datanode"
    environment:
      # https://hub.docker.com/r/graylog/graylog-datanode#configuration
      # https://go2docs.graylog.org/current/setting_up_graylog/data_node_configuration_file.htm
      GRAYLOG_DATANODE_OPENSEARCH_HEAP: 2g
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - graylog
    volumes:
      - graylog-datanode:/var/lib/graylog-datanode
    restart: "on-failure"

  # https://hub.docker.com/r/graylog/graylog/
  # For initial configuration password will be generated by system. Check console out put for it
  # Later on use password defined in your .env file
  # An example output is as below:
  #
  # It seems you are starting Graylog for the first time. To set up a fresh install, a setup interface has
  # drn-graylog           | been started. You must log in to it to perform the initial configuration and continue.
  # drn-graylog           |
  # drn-graylog           | Initial configuration is accessible at 0.0.0.0:9000, with username 'admin' and password 'vwtxJbPxqM'.
  # drn-graylog           | Try clicking on http://admin:vwtxJbPxqM@0.0.0.0:9000

  graylog:
    image: "${GRAYLOG_IMAGE:-graylog/graylog:6.3.2}"
    container_name: drn-graylog
    hostname: "server"
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: /usr/share/graylog/data/data/node-id
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_HTTP_EXTERNAL_URI: http://localhost:9000/
      GRAYLOG_MONGODB_URI: mongodb://mongodb:27017/graylog
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW UDP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      #- "10000:10000/tcp" # Custom TCP port
      #- "10000:10000/udp" # Custom UDP port
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    networks:
      - graylog
    volumes:
      - graylog_data:/usr/share/graylog/data/data
    restart: "on-failure"
    
networks:
  graylog:
    driver: "bridge"
    
# see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  graylog-mongodb_data:
  graylog-mongodb_config:
  graylog-datanode:
  graylog_data: