<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>Duran Serkan KILIÇ</Authors>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <PackageId>DRN.Framework.SharedKernel</PackageId>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/duranserkan/DRN-Project</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSymbols>true</IncludeSymbols>
        <EmbedAllSources>true</EmbedAllSources>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Update="RELEASE-NOTES.md">
          <Pack>True</Pack>
          <PackagePath>/</PackagePath>
        </None>
    </ItemGroup>

    <Target Name="PrepareDescription" BeforeTargets="GenerateNuspec">
        <PropertyGroup>
            <PackageDescription>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/PACKAGE-DESCRIPTION"))</PackageDescription>
        </PropertyGroup>
    </Target>

    <Target Name="PreparePackageReleaseNotes" BeforeTargets="GenerateNuspec">
        <PropertyGroup>
            <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/RELEASE-NOTES.md"))</PackageReleaseNotes>
        </PropertyGroup>
    </Target>

    <ItemGroup>
        <ProjectReference Include="..\DRN.Framework.SharedKernel.Analyzers\DRN.Framework.SharedKernel.Analyzers.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <None Update="buildTransitive/DRN.Framework.SharedKernel.props">
            <Pack>true</Pack>
            <PackagePath>buildTransitive/$(PackageId).props</PackagePath>
        </None>
        <None Update="buildTransitive/DRN.Framework.SharedKernel.targets">
            <Pack>true</Pack>
            <PackagePath>buildTransitive/$(PackageId).targets</PackagePath>
        </None>
        <None Update="build/DRN.Framework.SharedKernel.props">
            <Pack>true</Pack>
            <PackagePath>build/$(PackageId).props</PackagePath>
        </None>
        <None Update="build/DRN.Framework.SharedKernel.targets">
            <Pack>true</Pack>
            <PackagePath>build/$(PackageId).targets</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DRN.Test.Unit" />
        <InternalsVisibleTo Include="DRN.Test.Integration"/>
        <InternalsVisibleTo Include="DRN.Framework.Utils" />
        <InternalsVisibleTo Include="DRN.Framework.EntityFramework" />
        <InternalsVisibleTo Include="DRN.Framework.Testing"/>
    </ItemGroup>

</Project>