name: Setup SDK
runs:
  using: "composite"
  steps:
    - name: Sonar Scan End
      shell: pwsh
      run: |
        ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"