name: Dotnet Validate
description: "Set up .NET, build, and run unit and integration tests in Debug mode."
inputs:
  working-directory:
    description: "Repository directory containing the solution file."
    required: false
    default: "."
  solution-file:
    description: "Solution file to build and validate."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup SDK
      uses: ./.github/actions/setup-sdk-and-tools

    - name: Build
      uses: ./.github/actions/dotnet-build
      with:
        working-directory: ${{ inputs.working-directory }}
        solution-file: ${{ inputs.solution-file }}

    - name: Test
      uses: ./.github/actions/dotnet-test
      with:
        working-directory: ${{ inputs.working-directory }}
