name: Dotnet Test Release
runs:
  using: "composite"
  steps:
    - name: Test Unit
      shell: bash
      run: dotnet test DRN.Test.Unit/DRN.Test.Unit.csproj --no-build --verbosity normal --configuration Release
    - name: Test Integration
      shell: bash
      run: dotnet test DRN.Test/DRN.Test.csproj --no-build --verbosity normal --configuration Release