name: drn-postgres
services:
  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:18.6-alpine3.24@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    container_name: drn-postgres
    restart: unless-stopped
    volumes:
      - drn-postgres-data:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:? configure in the .env file}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:? configure in the .env file}
      POSTGRES_DB: ${POSTGRES_DB:-drn}
      PGDATA: ${PGDATA:-/data/postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  drn-postgres-data:
