<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DRN.Framework.Utils\DRN.Framework.Utils.csproj" />
  </ItemGroup>


  <ItemGroup>
    <InternalsVisibleTo Include="Sample.Hosted" />
    <InternalsVisibleTo Include="DRN.Test.Unit" />
    <InternalsVisibleTo Include="DRN.Test.Integration" />
  </ItemGroup>

</Project>