name: Nuget Publish
inputs:
  project-name:
    required: true
  project-version:
    required: true
  token:
    required: true
  commit-info:
    required: true
runs:
  using: "composite"
  steps:
    - name: Pack
      run: |
        ${{ commit-info }}  >>  ${{ inputs.project-name }}/PACKAGE-DESCRIPTION
        ${{ commit-info }}  >>  ${{ inputs.project-name }}/README.md
        ${{ commit-info }}  >>  ${{ inputs.project-name }}/RELEASE-NOTES.md
        dotnet pack ${{ inputs.project-name }}/${{ inputs.project-name }}.csproj --configuration Release /p:Version=${{ inputs.project-version }} --no-build --output .
    - name: Push
      run: |
        dotnet nuget push ${{ inputs.project-name }}.${{ inputs.project-version }}.nupkg --skip-duplicate --api-key ${{ inputs.token }} --source https://api.nuget.org/v3/index.json