name: Dotnet Build
runs:
  using: "composite"
  steps:
    - name: Restore dependencies
      shell: bash
      run: dotnet restore DRN.sln
    - name: Build solution
      shell: bash
      run: dotnet build DRN.sln --no-restore --no-incremental