name: Docker Publish
inputs:
  project-name:
    required: true
  image-repository-name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
      with:
          images: duranserkan/${{ inputs.image-repository-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
    - name: Build and push Docker image
      id: container-build-push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./${{ inputs.project-name }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        sbom: true
        provenance: true
    - name: Docker Scout
      id: docker-scout
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/scout-action@v1
      with:
        command: quickview,cves,recommendations
        sarif-file: sarif.${{ inputs.project-name }}.output.json
        summary: true
    - name: Upload SARIF result
      id: upload-container-sarif
      if: ${{ github.event_name != 'pull_request' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif.${{ inputs.project-name }}.output.json
        category: docker-scout-${{ inputs.project-name }}