name: Dotnet Test Debug
description: "Run Dotnet unit and integration tests in Debug mode without rebuilding."
inputs:
  working-directory:
    description: "Repository directory containing DRN.slnx."
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Test Unit
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        # Intentionally, telemetry is not disabled to support MS Testing Platform development in this CI pipeline
        TESTINGPLATFORM_TELEMETRY_OPTOUT: "0"
      run: dotnet run --project DRN.Test.Unit/DRN.Test.Unit.csproj --no-build --verbosity minimal
    - name: Test Integration
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        # Intentionally, telemetry is not disabled to support MS Testing Platform development in this CI pipeline
        TESTINGPLATFORM_TELEMETRY_OPTOUT: "0"
      run: dotnet run --project DRN.Test.Integration/DRN.Test.Integration.csproj --no-build --verbosity minimal
