namespace DRN.Framework.Utils.Settings;

/// <summary>
/// In production values will be obtained from nexus as a remote configuration source
/// </summary>
public class NexusAppSettings
{
    public static string GetKey(string shortKey) => $"{nameof(NexusAppSettings)}:{shortKey}";

    //Ids will be generated by Nexus App randomly in production
    public byte NexusAppId { get; init; }
    public byte NexusAppInstanceId { get; init; }

    public IReadOnlyList<NexusMacKey> MacKeys { get; init; } = new List<NexusMacKey>();
    public NexusMacKey GetDefaultMacKey() => MacKeys.First(x => x.Default);
}

public class NexusMacKey
{
    public byte[] Key { get; init; } = [];
    public bool Default { get; init; }
    public bool IsValid => Key.Length >= 32;
}