name: Nuget Publish All
runs:
  using: "composite"
  steps:
    - name: Publish SharedKernel
      uses: ./.github/workflows/actions/nuget-publish
      with:
        project-name: DRN.Framework.SharedKernel
    - name: Publish Utils
      uses: ./.github/workflows/actions/nuget-publish
      with:
        project-name: DRN.Framework.Utils
    - name: Publish EntityFramework
      uses: ./.github/workflows/actions/nuget-publish
      with:
        project-name: DRN.Framework.EntityFramework
    - name: Publish Hosting
      uses: ./.github/workflows/actions/nuget-publish
      with:
        project-name: DRN.Framework.Hosting
    - name: Publish Testing
      uses: ./.github/workflows/actions/nuget-publish
      with:
        project-name: DRN.Framework.Testing