# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: develop
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SDK
        uses: ./.github/workflows/actions/setup-sdk-and-tools

      - name: Build
        uses: ./.github/workflows/actions/dotnet-build

      - name: Test
        uses: ./.github/workflows/actions/dotnet-test