# this pipeline developed with the help of https://github.com/acraven/blog-nuget-workflow-github-actions/
name: release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Publish-Master:
    runs-on: ubuntu-latest
    env:
      SolutionName: DRN.sln
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/master
        run: git branch --remote --contains | grep origin/master
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore ${SolutionName}
      - name: Build
        run: dotnet build ${SolutionName} --configuration Release /p:Version=${VERSION} --no-restore
      - name: Test
        run: dotnet test ${ProjectName}/${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --verbosity normal
        env:
          ProjectName: DRN.Test
      - name: Push SharedKernel
        run: |
          git --no-pager log -1 --format="%n%an,  %ai, %C(auto)%H"  >>  ${ProjectName}/PACKAGE-DESCRIPTION
          dotnet pack ${ProjectName}/${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push ${ProjectName}.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
        env:
          ProjectName: DRN.Framework.SharedKernel
      - name: Push Utils
        run: |
          git --no-pager log -1 --format="%n%an,  %ai, %C(auto)%H"  >>  ${ProjectName}/PACKAGE-DESCRIPTION
          dotnet pack ${ProjectName}/${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push ${ProjectName}.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
        env:
          ProjectName: DRN.Framework.Utils
      - name: Push Testing
        run: |
          git --no-pager log -1 --format="%n%an,  %ai, %C(auto)%H"  >>  ${ProjectName}/PACKAGE-DESCRIPTION
          dotnet pack ${ProjectName}/${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push ${ProjectName}.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
        env:
          ProjectName: DRN.Framework.Testing