# this pipeline developed with the help of https://github.com/acraven/blog-nuget-workflow-github-actions/
name: release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Publish-Master:
    runs-on: ubuntu-latest
    env:
      SOLUTION_NAME: DRN.sln
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/master
        run: git branch --remote --contains | grep origin/master
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Set VERSION variable from tag
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore ${SOLUTION_NAME}
      - name: Build
        run: dotnet build ${SOLUTION_NAME} --configuration Release /p:Version=${VERSION} --no-restore
      - name: Test
        run: dotnet test ${ProjectName}/${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --verbosity normal
        env:
          ProjectName: DRN.Test
      - name: Publish SharedKernel
        uses: ./.github/workflows/actions/nuget-publish
        with:
          project-name: DRN.Framework.SharedKernel
      - name: Publish Utils
        uses: ./.github/workflows/actions/nuget-publish
        with:
          project-name: DRN.Framework.Utils
      - name: Publish Testing
        uses: ./.github/workflows/actions/nuget-publish
        with:
          project-name: DRN.Framework.Testing