# this pipeline developed with the help of https://github.com/acraven/blog-nuget-workflow-github-actions/
name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Publish-Master:
    permissions:
      security-events: write
      id-token: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    env:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify commit exists in origin/master
        run: git branch --remote --contains | grep origin/master

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Setup SDK
        uses: ./.github/workflows/actions/setup-sdk-and-tools

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp,javascript

      - name: Build
        uses: ./.github/workflows/actions/dotnet-build-release

      - name: Test
        uses: ./.github/workflows/actions/dotnet-test-release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Publish Packages
        uses: ./.github/workflows/actions/nuget-publish-all
      
      - name: Generate artifact attestation #https://andrewlock.net/creating-provenance-attestations-for-nuget-packages-in-github-actions/
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'artifacts/packages/*.nupkg'

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages

      - name: Publish Images
        uses: ./.github/workflows/actions/docker-publish-all