# this pipeline developed with the help of https://github.com/acraven/blog-nuget-workflow-github-actions/blob/main/.github/workflows/release.yml
name: release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Publish-Master:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/master
        run: git branch --remote --contains | grep origin/master
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore DRN.sln
      - name: Build
        run: dotnet build DRN.sln --configuration Release /p:Version=${VERSION} --no-restore
      - name: Test
        run: dotnet test DRN.Test/DRN.Test.csproj --configuration Release /p:Version=${VERSION} --no-build --verbosity normal
      - name: Push SharedKernel
        run: |
          echo "ProjectName=SharedKernel" >> $GITHUB_ENV
          git --no-pager log -1 --format="%n %C(auto)%H  %ai"  >>  DRN.Framework.${ProjectName}/PACKAGE-DESCRIPTION
          dotnet pack DRN.Framework.${ProjectName}/DRN.Framework.${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push DRN.Framework.${ProjectName}.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
      - name: Push Utils
        run: |
          echo "ProjectName=Utils" >> $GITHUB_ENV
          git --no-pager log -1 --format="%n %C(auto)%H  %ai"  >>  DRN.Framework.${ProjectName}/PACKAGE-DESCRIPTION
          dotnet pack DRN.Framework.${ProjectName}/DRN.Framework.${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push DRN.Framework.${ProjectName}.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
      - name: Push Testing
        run: |
          echo "ProjectName=Testing" >> $GITHUB_ENV
          git --no-pager log -1 --format="%n %C(auto)%H  %ai"  >>  DRN.Framework.${ProjectName}/PACKAGE-DESCRIPTION
          dotnet pack DRN.Framework.${ProjectName}/DRN.Framework.${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push DRN.Framework.${ProjectName}.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json