# this pipeline developed with the help of https://github.com/acraven/blog-nuget-workflow-github-actions/
name: release-preview
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]
jobs:
  Publish-Develop:
    runs-on: ubuntu-latest
    env:
      SolutionName: DRN.sln
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/develop
        run: git branch --remote --contains | grep origin/develop
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Set COMMIT-INFO and VERSION variable from tag
        run: |
          COMMIT_INFO=$(git --no-pager log -1 --format="%n%nAuthor, date, commit hash:%n%an,  %ai, %C(auto)%H")
          echo "COMMIT_INFO=${COMMIT_INFO}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore ${SolutionName}
      - name: Build
        run: dotnet build ${SolutionName} --configuration Release /p:Version=${VERSION} --no-restore
      - name: Test
        run: dotnet test ${ProjectName}/${ProjectName}.csproj --configuration Release /p:Version=${VERSION} --no-build --verbosity normal
        env:
          ProjectName: DRN.Test
      - name: Publish SharedKernel
        uses: ./.github/workflows/actions/nuget-publish
        with:
          project-name: DRN.Framework.SharedKernel
          project-version: ${VERSION}
          commit-info: ${COMMIT_INFO}
          token: ${{ secrets.NUGET_TOKEN }}
      - name: Publish Utils
        uses: ./.github/workflows/actions/nuget-publish
        with:
          project-name: DRN.Framework.Utils
          project-version: ${VERSION}
          commit-info: ${COMMIT_INFO}
          token: ${{ secrets.NUGET_TOKEN }}
      - name: Publish Testing
        uses: ./.github/workflows/actions/nuget-publish
        with:
          project-name: DRN.Framework.Utils
          project-version: ${VERSION}
          commit-info: ${COMMIT_INFO}
          token: ${{ secrets.NUGET_TOKEN }}