# this pipeline developed with the help of https://github.com/acraven/blog-nuget-workflow-github-actions/
name: release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Publish-Master:
    runs-on: ubuntu-latest
    env:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/master
        run: git branch --remote --contains | grep origin/master
      - name: Setup SDK
        uses: ./.github/workflows/actions/setup-sdk-and-tools
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        uses: ./.github/workflows/actions/dotnet-build-release
      - name: Test
        uses: ./.github/workflows/actions/dotnet-test-release
      - name: Publish Packages
        uses: ./.github/workflows/actions/nuget-publish-all