# this pipeline developed with the help of https://github.com/acraven/blog-nuget-workflow-github-actions/blob/main/.github/workflows/release.yml
name: release-preview
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]
jobs:
  Publish-Develop:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/develop
        run: git branch --remote --contains | grep origin/develop
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore DRN.sln
      - name: Build
        run: dotnet build DRN.sln --configuration Release /p:Version=${VERSION} --no-restore
      - name: Test
        run: dotnet test DRN.Test/DRN.Test.csproj --configuration Release /p:Version=${VERSION} --no-build --verbosity normal
      - name: Push SharedKernel
        run: |
          git --no-pager log -1 --format="%n %C(auto)%H  %ai"  >>  DRN.Framework.SharedKernel/PackageDescription
          dotnet pack DRN.Framework.SharedKernel/DRN.Framework.SharedKernel.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push DRN.Framework.SharedKernel.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
      - name: Push Utils
        run: |
          git --no-pager log -1 --format="%n %C(auto)%H  %ai"  >>  DRN.Framework.Utils/PackageDescription
          dotnet pack DRN.Framework.Utils/DRN.Framework.Utils.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push DRN.Framework.Utils.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
      - name: Push Testing
        run: |
          git --no-pager log -1 --format="%n %C(auto)%H  %ai"  >>  DRN.Framework.Testing/PackageDescription
          dotnet pack DRN.Framework.Testing/DRN.Framework.Testing.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet nuget push DRN.Framework.Testing.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json